<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="9" total="10" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="93744" started-at="2020-08-12T17:32:14Z" finished-at="2020-08-12T17:33:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="93744" started-at="2020-08-12T17:32:14Z" finished-at="2020-08-12T17:33:48Z">
      <class name="Test.NotificationTest">
        <test-method status="PASS" signature="setExtent()[pri:0, instance:Test.NotificationTest@2145433b]" name="setExtent" is-config="true" duration-ms="203" started-at="2020-08-12T17:32:14Z" finished-at="2020-08-12T17:32:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setExtent -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:Test.NotificationTest@2145433b]" name="setUp" is-config="true" duration-ms="17314" started-at="2020-08-12T17:32:14Z" finished-at="2020-08-12T17:32:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="validateTC_N_033()[pri:10, instance:Test.NotificationTest@2145433b]" name="validateTC_N_033" duration-ms="73873" started-at="2020-08-12T17:32:32Z" finished-at="2020-08-12T17:33:46Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [5]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Test.NotificationTest.validateTC_N_033(NotificationTest.java:634)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateTC_N_033 -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:Test.NotificationTest@2145433b]" name="tearDown" is-config="true" duration-ms="1634" started-at="2020-08-12T17:33:46Z" finished-at="2020-08-12T17:33:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validateTC_N_033 status=FAILURE method=NotificationTest.validateTC_N_033()[pri:10, instance:Test.NotificationTest@2145433b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="endReport()[pri:0, instance:Test.NotificationTest@2145433b]" name="endReport" is-config="true" duration-ms="686" started-at="2020-08-12T17:33:47Z" finished-at="2020-08-12T17:33:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- Test.NotificationTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
